
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CCOMILLA = 24;
  public static final int INTERROGACION = 18;
  public static final int GUION = 7;
  public static final int PUNTO = 15;
  public static final int DOSPUNTOS = 6;
  public static final int OR = 17;
  public static final int LETRA = 5;
  public static final int MAYORQUE = 8;
  public static final int COMILLAS = 23;
  public static final int TILDE = 10;
  public static final int PORCENTAJE = 21;
  public static final int CARACTER = 25;
  public static final int MINUSCULA = 12;
  public static final int COMA = 14;
  public static final int EOF = 0;
  public static final int ASTERISCO = 16;
  public static final int LLAVEABIERTA = 2;
  public static final int CONJ = 4;
  public static final int SIMBOLOS = 20;
  public static final int error = 1;
  public static final int NUMERO = 11;
  public static final int IDENTIFICADOR = 22;
  public static final int MAYUSCULA = 13;
  public static final int PUNTOCOMA = 9;
  public static final int MAS = 19;
  public static final int LLAVECERRADA = 3;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "LLAVEABIERTA",
  "LLAVECERRADA",
  "CONJ",
  "LETRA",
  "DOSPUNTOS",
  "GUION",
  "MAYORQUE",
  "PUNTOCOMA",
  "TILDE",
  "NUMERO",
  "MINUSCULA",
  "MAYUSCULA",
  "COMA",
  "PUNTO",
  "ASTERISCO",
  "OR",
  "INTERROGACION",
  "MAS",
  "SIMBOLOS",
  "PORCENTAJE",
  "IDENTIFICADOR",
  "COMILLAS",
  "CCOMILLA",
  "CARACTER"
  };
}

