
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DOSPUNTOS = 5;
  public static final int LETRA = 4;
  public static final int CONJ = 3;
  public static final int MAYUSCULA = 12;
  public static final int EOF = 0;
  public static final int MAYORQUE = 7;
  public static final int TILDE = 9;
  public static final int NUMERO = 10;
  public static final int GUION = 6;
  public static final int error = 1;
  public static final int PUNTOCOMA = 8;
  public static final int LLAVEABIERTA = 2;
  public static final int MINUSCULA = 11;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "LLAVEABIERTA",
  "CONJ",
  "LETRA",
  "DOSPUNTOS",
  "GUION",
  "MAYORQUE",
  "PUNTOCOMA",
  "TILDE",
  "NUMERO",
  "MINUSCULA",
  "MAYUSCULA"
  };
}

